apiVersion: v1
kind: ServiceAccount
metadata:
  name: magicpai-server
  namespace: magicpai
  labels:
    app.kubernetes.io/name: magicpai-server
    app.kubernetes.io/part-of: magicpai
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: magicpai-worker-manager
  namespace: magicpai
  labels:
    app.kubernetes.io/part-of: magicpai
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: magicpai-server-worker-manager
  namespace: magicpai
  labels:
    app.kubernetes.io/part-of: magicpai
subjects:
  - kind: ServiceAccount
    name: magicpai-server
    namespace: magicpai
roleRef:
  kind: Role
  name: magicpai-worker-manager
  apiGroup: rbac.authorization.k8s.io
